# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oLDUMhiHK35u5q_2FUVJwUdkNY2mXXh0
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q "https://downloads.apache.org/spark/spark-3.2.4/spark-3.2.4-bin-hadoop3.2.tgz"
!tar -xvf spark-3.2.4-bin-hadoop3.2.tgz
!pip install -q findspark
!pip install -q pyspark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.4-bin-hadoop3.2"
import findspark
findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

dataset = spark.read.csv('/content/sample_data/california_housing_test.csv',inferSchema=True, header =True)

dataset.printSchema()

dataset.head()

spark.stop()

from pyspark import SparkContext
spark_contexto = SparkContext()
print(spark_contexto)
print(spark_contexto.version)

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate() # Create my_spark
print(spark) # Print my_spark

dataset = spark.read.csv('/content/sample_data/california_housing_test.csv',inferSchema=True, header =True)
dataset.head()

dataset.count()

dataset.createOrReplaceTempView("tabela_temporaria")
print(spark.catalog.listTables())

query = "FROM tabela_temporaria SELECT longitude, latitude LIMIT 3"
saida = spark.sql(query)
saida.show()

